# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/igor/Downloads/PAMSIproj3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/igor/Downloads/PAMSIproj3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/igor/Downloads/PAMSIproj3/CMakeFiles /home/igor/Downloads/PAMSIproj3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/igor/Downloads/PAMSIproj3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PAMSIproj3

# Build rule for target.
PAMSIproj3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PAMSIproj3
.PHONY : PAMSIproj3

# fast build rule for target.
PAMSIproj3/fast:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/build
.PHONY : PAMSIproj3/fast

checkersBoard.o: checkersBoard.cpp.o

.PHONY : checkersBoard.o

# target to build an object file
checkersBoard.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/checkersBoard.cpp.o
.PHONY : checkersBoard.cpp.o

checkersBoard.i: checkersBoard.cpp.i

.PHONY : checkersBoard.i

# target to preprocess a source file
checkersBoard.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/checkersBoard.cpp.i
.PHONY : checkersBoard.cpp.i

checkersBoard.s: checkersBoard.cpp.s

.PHONY : checkersBoard.s

# target to generate assembly for a file
checkersBoard.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/checkersBoard.cpp.s
.PHONY : checkersBoard.cpp.s

field.o: field.cpp.o

.PHONY : field.o

# target to build an object file
field.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/field.cpp.o
.PHONY : field.cpp.o

field.i: field.cpp.i

.PHONY : field.i

# target to preprocess a source file
field.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/field.cpp.i
.PHONY : field.cpp.i

field.s: field.cpp.s

.PHONY : field.s

# target to generate assembly for a file
field.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/field.cpp.s
.PHONY : field.cpp.s

heuristics_function.o: heuristics_function.cpp.o

.PHONY : heuristics_function.o

# target to build an object file
heuristics_function.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/heuristics_function.cpp.o
.PHONY : heuristics_function.cpp.o

heuristics_function.i: heuristics_function.cpp.i

.PHONY : heuristics_function.i

# target to preprocess a source file
heuristics_function.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/heuristics_function.cpp.i
.PHONY : heuristics_function.cpp.i

heuristics_function.s: heuristics_function.cpp.s

.PHONY : heuristics_function.s

# target to generate assembly for a file
heuristics_function.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/heuristics_function.cpp.s
.PHONY : heuristics_function.cpp.s

input_to_move_vector.o: input_to_move_vector.cpp.o

.PHONY : input_to_move_vector.o

# target to build an object file
input_to_move_vector.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/input_to_move_vector.cpp.o
.PHONY : input_to_move_vector.cpp.o

input_to_move_vector.i: input_to_move_vector.cpp.i

.PHONY : input_to_move_vector.i

# target to preprocess a source file
input_to_move_vector.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/input_to_move_vector.cpp.i
.PHONY : input_to_move_vector.cpp.i

input_to_move_vector.s: input_to_move_vector.cpp.s

.PHONY : input_to_move_vector.s

# target to generate assembly for a file
input_to_move_vector.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/input_to_move_vector.cpp.s
.PHONY : input_to_move_vector.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/main.cpp.s
.PHONY : main.cpp.s

moveTree.o: moveTree.cpp.o

.PHONY : moveTree.o

# target to build an object file
moveTree.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/moveTree.cpp.o
.PHONY : moveTree.cpp.o

moveTree.i: moveTree.cpp.i

.PHONY : moveTree.i

# target to preprocess a source file
moveTree.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/moveTree.cpp.i
.PHONY : moveTree.cpp.i

moveTree.s: moveTree.cpp.s

.PHONY : moveTree.s

# target to generate assembly for a file
moveTree.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/moveTree.cpp.s
.PHONY : moveTree.cpp.s

move_vector_to_output.o: move_vector_to_output.cpp.o

.PHONY : move_vector_to_output.o

# target to build an object file
move_vector_to_output.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/move_vector_to_output.cpp.o
.PHONY : move_vector_to_output.cpp.o

move_vector_to_output.i: move_vector_to_output.cpp.i

.PHONY : move_vector_to_output.i

# target to preprocess a source file
move_vector_to_output.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/move_vector_to_output.cpp.i
.PHONY : move_vector_to_output.cpp.i

move_vector_to_output.s: move_vector_to_output.cpp.s

.PHONY : move_vector_to_output.s

# target to generate assembly for a file
move_vector_to_output.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/move_vector_to_output.cpp.s
.PHONY : move_vector_to_output.cpp.s

piece_char.o: piece_char.cpp.o

.PHONY : piece_char.o

# target to build an object file
piece_char.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/piece_char.cpp.o
.PHONY : piece_char.cpp.o

piece_char.i: piece_char.cpp.i

.PHONY : piece_char.i

# target to preprocess a source file
piece_char.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/piece_char.cpp.i
.PHONY : piece_char.cpp.i

piece_char.s: piece_char.cpp.s

.PHONY : piece_char.s

# target to generate assembly for a file
piece_char.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/piece_char.cpp.s
.PHONY : piece_char.cpp.s

possible_moves.o: possible_moves.cpp.o

.PHONY : possible_moves.o

# target to build an object file
possible_moves.cpp.o:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/possible_moves.cpp.o
.PHONY : possible_moves.cpp.o

possible_moves.i: possible_moves.cpp.i

.PHONY : possible_moves.i

# target to preprocess a source file
possible_moves.cpp.i:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/possible_moves.cpp.i
.PHONY : possible_moves.cpp.i

possible_moves.s: possible_moves.cpp.s

.PHONY : possible_moves.s

# target to generate assembly for a file
possible_moves.cpp.s:
	$(MAKE) -f CMakeFiles/PAMSIproj3.dir/build.make CMakeFiles/PAMSIproj3.dir/possible_moves.cpp.s
.PHONY : possible_moves.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PAMSIproj3"
	@echo "... checkersBoard.o"
	@echo "... checkersBoard.i"
	@echo "... checkersBoard.s"
	@echo "... field.o"
	@echo "... field.i"
	@echo "... field.s"
	@echo "... heuristics_function.o"
	@echo "... heuristics_function.i"
	@echo "... heuristics_function.s"
	@echo "... input_to_move_vector.o"
	@echo "... input_to_move_vector.i"
	@echo "... input_to_move_vector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moveTree.o"
	@echo "... moveTree.i"
	@echo "... moveTree.s"
	@echo "... move_vector_to_output.o"
	@echo "... move_vector_to_output.i"
	@echo "... move_vector_to_output.s"
	@echo "... piece_char.o"
	@echo "... piece_char.i"
	@echo "... piece_char.s"
	@echo "... possible_moves.o"
	@echo "... possible_moves.i"
	@echo "... possible_moves.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

